alias gz="cd ~/.config/zsh"
alias gc="cd ~/.config"
alias gn="cd ~/.config/nvim"
alias gi="cd ~/.config/i3"
alias gd="cd ~/Desktop"
alias g/="cd /"
alias c="clear"
alias mk="mkdir"
alias vim="/bin/nvim"
alias v="vim"
alias n="neofetch"
alias ra="ranger"
alias ls="ls --color=auto"
alias ll="ls -l --color=auto"

alias gl="git log --color --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit"
alias sp='. $HOME/.config/StartUp/StartUp.sh'
alias lg="lazygit"
alias ta="tmux attach"
alias tmuxp-stop="tmux kill-session -t"
